// Code généré automatiquement. Ne pas modifier.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "personnage0":return img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`;
            case "/YMc*0@r,nlsCFkh%Snt":
            case "personnage":return img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.ffefbf44fbfeff.........
.fee4dddddd4eef.........
fdfeeddddd4eeff.........
fbffee4444ee4f..........
fbf4f222222f1e..........
fcf.f222222f44..........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
`;
            case "image3":
            case "jarre":return img`
....................
....................
....................
....................
....................
....................
.....7977777777.....
.....7777777777.....
......66666666......
......99999999......
.....9999999999.....
.....9999999999.....
.....9999999999.....
.....9999999999.....
.....9999999999.....
.....9999999999.....
.....9999999999.....
......77777777......
....................
....................
`;
            case "image2":
            case "gant":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . 5 . 5 . 5 . 5 . . . . . 
. . . . 5 . 5 . 5 . 5 . . . . . 
. . 5 . 5 . 5 . 5 . 5 . . . . . 
. . 5 . 5 . 5 . 5 . 5 . . . . . 
. . 5 . 5 . 5 . 5 . 5 . . . . . 
. . 6 5 2 5 7 5 4 5 a . . . . . 
. . . . . 5 9 9 9 5 . . . . . . 
. . . . . 5 9 9 9 5 . . . . . . 
. . . . . 5 9 9 9 5 . . . . . . 
. . . . . 5 9 9 9 5 . . . . . . 
. . . . . 5 9 9 9 5 . . . . . . 
. . . . . 5 9 9 9 5 . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Code généré automatiquement. Ne pas modifier.
